# Generated by Django 6.0.3 on 2026-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
